language: java
jdk: openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="e68bacda-60dc-4860-b3c4-2d203e96af55"

cache:
  directories:
    - $HOME/.m2

