language: java
jdk: openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "janmalch-github" # the key of the org
script:
  - sonar-scanner
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - $HOME/.m2

