language: java
jdk: openjdk11

sudo: false # faster builds
install: true

addons:
  sonarcloud:
    organization: "janmalch-github" # the key of the org

script:
  - mvn clean deploy
  - sonar-scanner
# - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
 - bash <(curl -s https://codecov.io/bash)
