/**
 * Kino API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PresentationDto } from './presentationDto';
import { PriceCategoryDto } from './priceCategoryDto';


export interface MovieDto { 
    id?: number;
    name?: string;
    priceCategory?: PriceCategoryDto;
    startDate?: string;
    endDate?: string;
    duration?: number;
    ageRating?: number;
    presentations?: Array<PresentationDto>;
}
