/**
 * Kino API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SafeAccountInfoDto { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    role?: SafeAccountInfoDto.RoleEnum;
}
export namespace SafeAccountInfoDto {
    export type RoleEnum = 'ADMIN' | 'MODERATOR' | 'CUSTOMER' | 'GUEST';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        MODERATOR: 'MODERATOR' as RoleEnum,
        CUSTOMER: 'CUSTOMER' as RoleEnum,
        GUEST: 'GUEST' as RoleEnum
    };
}
